export let vesselTypesDict = {
    0: { color: "#999999", description: "Not available" },
    10: { color: "#FFFFFF", description: "Reserved" },
    11: { color: "#FFFFFF", description: "Reserved" },
    12: { color: "#FFFFFF", description: "Reserved" },
    13: { color: "#FFFFFF", description: "Reserved" },
    14: { color: "#FFFFFF", description: "Reserved" },
    15: { color: "#FFFFFF", description: "Reserved" },
    16: { color: "#FFFFFF", description: "Reserved" },
    17: { color: "#FFFFFF", description: "Reserved" },
    18: { color: "#FFFFFF", description: "Reserved" },
    19: { color: "#FFFFFF", description: "Reserved" },
    20: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Hazardous category A",
    },
    21: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Hazardous category B",
    },
    22: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Hazardous category C",
    },
    23: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Hazardous category D",
    },
    24: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    25: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    26: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    27: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    28: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    29: {
        color: "#FFA500",
        description: "Wing in ground (WIG), Reserved for future use",
    },
    30: { color: "#FF11AA", description: "Fishing" },
    31: { color: "#FF11AA", description: "Towing" },
    32: { color: "#FF11AA", description: "Towing (large)" },
    33: { color: "#FF11AA", description: "Dredging or underwater ops" },
    34: { color: "#FF11AA", description: "Diving ops" },
    35: { color: "#FF11AA", description: "Military ops" },
    36: { color: "#FF11AA", description: "Sailing" },
    37: { color: "#FF11AA", description: "Pleasure craft" },
    38: { color: "#FF11AA", description: "Reserved" },
    39: { color: "#FF11AA", description: "Reserved" },
    40: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Hazardous category B",
    },
    41: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Hazardous category C",
    },
    42: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Hazardous category D",
    },
    43: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    44: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    45: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    46: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    47: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    48: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    49: {
        color: "#FFFF00",
        description: "High speed craft (HSC), Reserved for future use",
    },
    50: { color: "#FFA500", description: "Pilot vessel" },
    51: { color: "#FFA500", description: "Search and rescue vessel" },
    52: { color: "#FFA500", description: "Tug" },
    53: { color: "#FFA500", description: "Port tender" },
    54: { color: "#FFA500", description: "Anti-pollution equipment" },
    55: { color: "#FFA500", description: "Law enforcement" },
    56: { color: "#FFA500", description: "Local vessel" },
    57: { color: "#FFA500", description: "Local vessel" },
    58: { color: "#FFA500", description: "Medical transport" },
    59: { color: "#FFA500", description: "Special craft" },
    60: { color: "#FF00FF", description: "Passenger ship" },
    61: { color: "#FF00FF", description: "Passenger ship" },
    62: { color: "#FF00FF", description: "Passenger ship" },
    63: { color: "#FF00FF", description: "Passenger ship" },
    64: { color: "#FF00FF", description: "Passenger ship" },
    65: { color: "#FF00FF", description: "Passenger ship" },
    66: { color: "#FF00FF", description: "Passenger ship" },
    67: { color: "#FF00FF", description: "Passenger ship" },
    68: { color: "#FF00FF", description: "Passenger ship" },
    69: { color: "#FF00FF", description: "Passenger ship" },
    70: { color: "#FF00FF", description: "Cargo ship" },
    71: { color: "#FF00FF", description: "Cargo ship" },
    72: { color: "#FF00FF", description: "Cargo ship" },
    73: { color: "#FF00FF", description: "Cargo ship" },
    74: { color: "#FF00FF", description: "Cargo ship" },
    75: { color: "#FF00FF", description: "Cargo ship" },
    76: { color: "#FF00FF", description: "Cargo ship" },
    77: { color: "#FF00FF", description: "Cargo ship" },
    78: { color: "#FF00FF", description: "Cargo ship" },
    79: { color: "#FF00FF", description: "Cargo ship" },
    80: { color: "#00FFFF", description: "Tanker" },
    81: { color: "#00FFFF", description: "Tanker" },
    82: { color: "#00FFFF", description: "Tanker" },
    83: { color: "#00FFFF", description: "Tanker" },
    84: { color: "#00FFFF", description: "Tanker" },
    85: { color: "#00FFFF", description: "Tanker" },
    86: { color: "#00FFFF", description: "Tanker" },
    87: { color: "#00FFFF", description: "Tanker" },
    88: { color: "#00FFFF", description: "Tanker" },
    89: { color: "#00FFFF", description: "Tanker" },
    90: { color: "#008000", description: "Other Type" },
    91: { color: "#008000", description: "Other Type" },
    92: { color: "#008000", description: "Other Type" },
    93: { color: "#008000", description: "Other Type" },
    94: { color: "#008000", description: "Other Type" },
    95: { color: "#008000", description: "Other Type" },
    96: { color: "#008000", description: "Other Type" },
    97: { color: "#008000", description: "Other Type" },
    98: { color: "#008000", description: "Other Type" },
    99: { color: "#008000", description: "Other Type" },
};
